[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://maxmarketpros.com/*"
  to = "https://www.maxmarketpros.com/:splat"
  status = 301
  force = true
