"use client"

import { useState } from "react"
import { SectionHeader } from "@/components/ui/section-header"
import { SecondaryButton } from "@/components/ui/secondary-button"
import { ChevronDown } from "lucide-react"

const CC_BLUE = "#1677FF"

type Faq = { q: string; a: React.ReactNode; aText: string }

export const customCodedFaqs: Faq[] = [
  {
    q: "What does “custom coded website” actually mean?",
    aText:
      "It means every line of HTML, CSS, JavaScript, and TypeScript on your site was written by hand by a developer — not generated by a drag-and-drop builder, not assembled from pre-built blocks, not based on a theme. We design components from scratch in React and Next.js, style them with Tailwind, deploy to Vercel's edge, and hand off the codebase to you. You can host it yourself, hire any agency to maintain it, or hand it to your in-house team.",
    a: (
      <>
        It means every line of HTML, CSS, JavaScript, and TypeScript on your
        site was written by hand by a developer — not generated by a
        drag-and-drop builder, not assembled from pre-built blocks, not based on
        a theme. We design components from scratch in{" "}
        <strong style={{ color: "var(--ink)" }}>React</strong> and{" "}
        <strong style={{ color: "var(--ink)" }}>Next.js</strong>, style them
        with Tailwind, deploy to Vercel&rsquo;s edge, and hand off the codebase
        to you.
      </>
    ),
  },
  {
    q: "How is a custom coded website different from Squarespace, Wix, or Webflow?",
    aText:
      "Builders like Squarespace, Wix, and Webflow give you a visual interface that generates code on your behalf. That code is opinionated, tied to the platform, and capped at the platform's performance ceiling. A custom coded website starts from an empty file. You're not paying a platform tax, you're not stuck with bundle bloat from features you don't use, and you can ship features (custom auth, complex APIs, real animation) that builders simply can't.",
    a: (
      <>
        Builders give you a visual interface that generates code on your
        behalf. That code is opinionated, tied to the platform, and capped at
        the platform&rsquo;s performance ceiling. A{" "}
        <strong>custom coded website</strong> starts from an empty file —
        you&rsquo;re not paying a platform tax, not stuck with bundle bloat, and
        can ship features builders can&rsquo;t. Compare side-by-side with{" "}
        <a
          href="/services/web-design/squarespace"
          style={{ color: CC_BLUE, fontWeight: 600 }}
        >
          Squarespace
        </a>
        ,{" "}
        <a
          href="/services/web-design/wix"
          style={{ color: CC_BLUE, fontWeight: 600 }}
        >
          Wix
        </a>
        , or{" "}
        <a
          href="/services/web-design/webflow"
          style={{ color: CC_BLUE, fontWeight: 600 }}
        >
          Webflow
        </a>
        .
      </>
    ),
  },
  {
    q: "How long does a custom coded website take to build?",
    aText:
      "Six weeks for a typical service-business build (10–15 unique page templates, headless CMS, full SEO foundation, hosting setup, and 30 days of post-launch support). Larger builds with custom auth, complex e-commerce, or 30+ unique templates run 8–12 weeks. We give you a fixed delivery date inside the kickoff call, scope what we can ship by that date, and hit it.",
    a: (
      <>
        Six weeks for a typical service-business build (10&ndash;15 unique page
        templates, headless CMS, full SEO foundation, hosting setup, and 30 days
        of post-launch support). Larger builds with custom auth, complex
        e-commerce, or 30+ unique templates run 8&ndash;12 weeks. We give you a
        fixed delivery date inside the kickoff call &mdash; and hit it.
      </>
    ),
  },
  {
    q: "Will I own the code when we’re done?",
    aText:
      "Yes — completely. The repository is in your GitHub organization (or transferred to it on launch day). Hosting and CMS billing live under your account, not ours. The Stripe, Sanity, and Resend keys are yours. If you fire us tomorrow, every part of your custom coded website continues to run, and any other dev shop can pick it up — because we use a stack the entire industry knows (Next.js, React, TypeScript, Tailwind).",
    a: (
      <>
        Yes &mdash; completely. The repository is in your GitHub organization,
        hosting and CMS billing live under your account, and the Stripe, Sanity,
        and Resend keys are yours. If you fire us tomorrow, your{" "}
        <strong>custom coded website</strong> continues to run, and any other
        dev shop can pick it up &mdash; because we use a stack the entire
        industry knows.
      </>
    ),
  },
  {
    q: "Can I edit content myself without touching code?",
    aText:
      "Yes — that's exactly what the headless CMS is for. We model your content (services, locations, blog posts, case studies, team, FAQs) inside Sanity (or another headless CMS of your choice), with a simple UI for editing text, swapping images, scheduling posts, and previewing changes before publishing. Non-technical team members handle 95% of day-to-day updates without a developer in the loop.",
    a: (
      <>
        Yes &mdash; that&rsquo;s exactly what the headless CMS is for. We model
        your content (services, locations, blog posts, case studies, team, FAQs)
        inside <strong style={{ color: "var(--ink)" }}>Sanity</strong>, with a
        simple UI for editing text, swapping images, scheduling posts, and
        previewing before publishing. Non-technical team members handle 95% of
        day-to-day updates without a developer in the loop.
      </>
    ),
  },
  {
    q: "How fast will my custom coded website be?",
    aText:
      "Lighthouse 100s on mobile, every category, every time we ship. Real numbers from our recent builds: LCP under 1.0s, TTI under 1.5s, JS bundle under 50 kB, total page weight under 200 kB. We hit those numbers because the page is server-rendered at the edge, images are auto-optimized to AVIF/WebP, fonts are subset and self-hosted, and there are zero third-party scripts we don't need.",
    a: (
      <>
        Lighthouse 100s on mobile, every category, every time we ship. Real
        numbers from our recent builds: LCP under 1.0s, TTI under 1.5s, JS
        bundle under 50 kB, total page weight under 200 kB. We hit those numbers
        because the page is server-rendered at the edge, images are
        auto-optimized to AVIF/WebP, fonts are subset and self-hosted, and there
        are zero third-party scripts we don&rsquo;t need.
      </>
    ),
  },
  {
    q: "What does ongoing support look like after launch?",
    aText:
      "Every custom coded website we ship comes with 30 days of post-launch support included — bug fixes, content tweaks, SEO checks, analytics review. Beyond that we offer a fixed monthly retainer for ongoing iteration: new pages, A/B tests, conversion optimization, performance monitoring, and content updates. Or you can hand the codebase to your in-house team — it's standard Next.js, any senior React developer can take over.",
    a: (
      <>
        Every custom coded website we ship comes with 30 days of post-launch
        support included. Beyond that we offer a fixed monthly retainer for
        ongoing iteration &mdash; new pages, A/B tests, conversion optimization,
        performance monitoring, and content updates. Or hand the codebase to
        your in-house team; it&rsquo;s standard Next.js, any senior React
        developer can take over.
      </>
    ),
  },
  {
    q: "Do you migrate from WordPress, Squarespace, or Wix to a custom coded stack?",
    aText:
      "Yes. Every migration includes a 301 redirect map (every old URL → new URL), a content audit (we don't ship duplicate or thin pages forward), CMS modeling for any dynamic content, an indexing check after launch, and a zero-downtime DNS cutover window. Most businesses see traffic recover or grow within 30 days of migrating to a custom coded website. We've migrated dozens of sites between platforms — the trickiest part is usually the redirect map for /blog/ archives, and we handle it in-house.",
    a: (
      <>
        Yes. Every migration includes a 301 redirect map, content audit, CMS
        modeling for dynamic content, an indexing check, and a zero-downtime DNS
        cutover. Most businesses see traffic recover or grow within 30 days of
        migrating to a <strong>custom coded website</strong>. Read the
        platform-specific guides:{" "}
        <a
          href="/services/web-design/wordpress"
          style={{ color: CC_BLUE, fontWeight: 600 }}
        >
          WordPress
        </a>
        ,{" "}
        <a
          href="/services/web-design/squarespace"
          style={{ color: CC_BLUE, fontWeight: 600 }}
        >
          Squarespace
        </a>
        , or{" "}
        <a
          href="/services/web-design/wix"
          style={{ color: CC_BLUE, fontWeight: 600 }}
        >
          Wix
        </a>
        .
      </>
    ),
  },
]

export function CustomCodedFaq() {
  const [openIdx, setOpenIdx] = useState<number | null>(0)

  return (
    <section
      id="custom-coded-faq"
      aria-labelledby="custom-coded-faq-heading"
      className="relative"
      style={{ background: "var(--bg)" }}
    >
      <div className="section-container section-y">
        <SectionHeader
          pill="Custom coded websites FAQ"
          heading={
            <span id="custom-coded-faq-heading">
              Real answers, before you{" "}
              <span className="whitespace-nowrap">
                <span
                  style={{
                    backgroundImage:
                      "linear-gradient(180deg, transparent 65%, rgba(22,119,255,0.30) 65%)",
                    paddingLeft: 4,
                    paddingRight: 4,
                  }}
                >
                  commit a budget
                </span>
                .
              </span>
            </span>
          }
          paragraph="The most common questions we get from teams researching custom coded websites — ownership, timeline, performance, content editing, and migrations."
        />

        <div
          className="mt-12 max-w-[860px] mx-auto"
          style={{ animation: "fadeInUp 0.7s ease-out both" }}
        >
          <ul className="space-y-3">
            {customCodedFaqs.map((faq, idx) => {
              const isOpen = openIdx === idx
              const num = `Q${String(idx + 1).padStart(2, "0")}`
              return (
                <li
                  key={faq.q}
                  className="card-surface overflow-hidden"
                  style={{ borderRadius: "var(--radius-lg)" }}
                >
                  <button
                    type="button"
                    aria-expanded={isOpen}
                    onClick={() => setOpenIdx(isOpen ? null : idx)}
                    className="w-full flex items-start gap-4 px-5 sm:px-6 py-5 text-left cursor-pointer hover:bg-[var(--bg)] transition-colors"
                  >
                    <span
                      className="shrink-0 inline-flex items-center justify-center px-2 py-1 rounded-md text-[11px] font-bold font-mono tracking-[0.05em]"
                      style={{
                        background: isOpen
                          ? `linear-gradient(180deg, #2B8AFF 0%, ${CC_BLUE} 100%)`
                          : "rgba(22,119,255,0.10)",
                        color: isOpen ? "#fff" : CC_BLUE,
                        minWidth: 36,
                      }}
                    >
                      {num}
                    </span>
                    <span
                      className="flex-1 text-[16px] sm:text-[17.5px] font-semibold leading-[1.35] pt-0.5"
                      style={{ color: "var(--ink)" }}
                    >
                      {faq.q}
                    </span>
                    <ChevronDown
                      className="shrink-0 w-5 h-5 mt-1 transition-transform duration-300"
                      strokeWidth={2.25}
                      style={{
                        color: isOpen ? CC_BLUE : "var(--muted)",
                        transform: isOpen ? "rotate(180deg)" : "rotate(0deg)",
                      }}
                    />
                  </button>
                  <div
                    className={`grid transition-all duration-300 ease-out ${
                      isOpen
                        ? "grid-rows-[1fr] opacity-100"
                        : "grid-rows-[0fr] opacity-0"
                    }`}
                  >
                    <div className="overflow-hidden">
                      <div
                        className="px-5 sm:px-6 pb-6 pl-[68px] sm:pl-[80px] text-[15px] sm:text-[16px] leading-[1.65]"
                        style={{ color: "var(--muted)" }}
                      >
                        {faq.a}
                      </div>
                    </div>
                  </div>
                </li>
              )
            })}
          </ul>

          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-3 text-center">
            <span className="text-[15.5px]" style={{ color: "var(--muted)" }}>
              Still have questions?
            </span>
            <SecondaryButton asLink href="#contact">
              Talk to a custom coded strategist
            </SecondaryButton>
          </div>
        </div>
      </div>
    </section>
  )
}

export function CustomCodedFaqJsonLd() {
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: customCodedFaqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.aText },
    })),
  }
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
    />
  )
}
